### ISSUE TITLE
Add sanity check

### ISSUE THREAD

**Issue by wucke13** [dschulte/geschwindigkeitsmessanlage#1]
You actually get four points in time. Use that! Both sensors generate a rising and a falling edge. Measure the time from rising to rising and the time from falling to falling, and compare them. That way you get another sanity check. Here is a brief example which implements that:

```
#include <stdint.h>
#include <stdio.h>

// All speed is stored in 1/10 fractions of Km/h
const uint16_t SPEED_SCALE = 100;

// How many ticks in the time variable rensemble 1 second?
const uint64_t TIME_SCALE = 1000;

// Allowed tolerance of error in our measurement
const uint16_t TOL = 1.5 * SPEED_SCALE;

// Common numerator among the speed equation (s/t)
// SPEED_SCALE * TIME_SCALE * lenght m/s to kmh
const uint64_t NUMERATOR = SPEED_SCALE * TIME_SCALE * 1. * 3.6;

#define absolute_delta(A, B) A > B ? A - B : B - A

// speed implementation sanity check
// speed_rising and speed_falling differ by more than TOL, the result will 0.
uint16_t speed(uint64_t s0_r, uint64_t s0_f, uint64_t s1_r, uint64_t s1_f) {
  // absolute of delta t between the two rising edges
  uint64_t td_r = absolute_delta(s0_r, s1_r);

  // absolute of delta t between the two falling edges
  uint64_t td_f = absolute_delta(s0_f, s1_f);

  // speed according to rising delta t
  uint64_t speed_r = NUMERATOR / td_r;

  // speed according to falling delta t
  uint64_t speed_f = NUMERATOR / td_f;

  // if estimated error is bigger than TOL, return 0 AKA "invalid"
  return absolute_delta(speed_r, speed_f) > TOL ? 0 : speed_r;
}

int main() {
  printf("%f\n",
         (float)speed(0, 0, 1 * TIME_SCALE, 1 * TIME_SCALE) / SPEED_SCALE);
  printf("%f\n",
         (float)speed(0, 0, 0.5 * TIME_SCALE, 0.5 * TIME_SCALE) / SPEED_SCALE);
  printf("%f\n",
         (float)speed(0, 0, 40 * TIME_SCALE, 40 * TIME_SCALE) / SPEED_SCALE);
}
```

In general I would avoid the use of floating point numbers on the Arduinos, as the Atmel 8 Bit MCUs do not come with a FPU AFAIK.

Other than that, you could also try to look at the time from rising to falling on one sensor. Assuming that Fynn's profile has at least a length of 15cm = 0.15m and he is not running faster than 250 Km/h = 69 m/s, we may estimate that the rising to falling on one sensor may not be shorter than 2.16 ms = 0.00216 s . That may not be such a helpful constraint, but Fynn ain't gonna run 69 m/s anyways. Depending on our knowledge about the vehicle to be tested, we may estimate at least some information about this. What actually is more fun is, that we could use the speed together with the rising to rising time to calculate the length of the measured object. Doesn't that sound fun?

**Comment by dschulte** [comment]
Moin! Ich schreib mal auf deutsch, da du aus Deutschland kommst, die Anleitung auch auf deutsch ist und vermutlich 99,9% der Besucher über das Video hierher kommen. Sollte sich das in Zukunft ändern, kann man natürlich auf englisch umschwenken.

**rising/falling**
Auf den ersten Blick scheint es sinnvoll zu sein, beide Flanken zu nutzen. Allerdings ist die "Rückseite" eines Objekts deutlich undefinierter als die Front, sodass das vermutlich mehr Fehlalarme verursachen würde als es evtl. nutzt. Beispielsweise fährt jemand mit einer flatternden Weste. Vorne ist eigentlich immer was festes. Optimalerweise misst man vermutlich nah am Boden auf Höhe der Reifen.

Eine sinnvolle Erweiterung wäre eine dritte Lichtschranke. So hat man zwei Messwerte und kann Fehlmessungen aussortieren, da die Geschwindigkeitsänderung des Objekts im Messbereich nur minimal sein wird. Wenn die beiden Messwerte also stark voneinander abweichen, kann man davon ausgehen, dass mit der Messung etwas nicht stimmt. Die Erweiterung werde ich vermutlich irgendwann noch umsetzen um die Messungen plausibler zu machen.

**floats**
Es ist auf jeden Fall sinnvoll ohne floats zu rechnen, wenn es auf Performance ankommt. Da das hier nicht der Fall ist, ist der Code mit floats deutlich verständlicher, da man dann so rechnen kann, wie man es in der Realität auch tut. Wenn die Berechnungen so oft wie möglich ausgeführt werden müssten, dann klar. Aber hier werden die bei jeder Messung genau ein Mal ausgeführt. Und ein Wert von 137,6  als Geschwindigkeit ist deutlich schneller und fehlerfreier zu verstehen als 1376.

Das Projekt ist sicherlich nicht perfekt. Für die Zwecke, für die es eingesetzt wird, funktioniert es aber schon ziemlich gut. Auf jeden Fall vielen Dank für deine Ausführungen. Es gibt bestimmt noch einiges zu verbessern und zu erweitern. Ich bin mit nicht sicher, ob ich jetzt auf alles genau genug eingegangen bin. Falls nicht, meld dich 😉

**Comment by wucke13** [comment]
Alles klar. Im allgemeinen würde ich auch noch mal durchrechnen, ob es sich lohnt von den ollen Arduino "Interrupts" weg zu kommen. Zeiten kann man damit nicht so besonders genau messen. Eleganter wäre es IMHO, wenn man zwei der HW-Interrupt Pins des Atmel zusammen mit dem input capture register von einem 16 Bit Timer einsetzt. Dann ist die Messungenauigkeit ausschließlich eine Frage des Quarz. Man verliert halt Kompatibilität zu anderen Boards, wobei sich das sicherlich mit dem Präprozessor wieder erkaufen lässt. 

Die undefinierte Rückseite ist natürlich vom Objekt abhängig. Ein Moped ist hinten nicht sonderlich weniger definiert als vorne. Falls du "Löcher" in der Strukture des Objektes, könnte man das wohl sanig umgehen wenn man einfach alle Edges in einer gewissen Zeit (3 s ohne neue Edge?) misst, und nur die letzte Falling davon betrachtet (jeweils an beiden Sensoren). Wenn eine Flatternde Weste konsistent ungültige Messungen erzeugt, ist wohl ein Performance-Strip angebracht :laughing:

**Comment by dschulte** [comment]
**Interrupts**
Ich benutze schon Hardware Pin Change Interrupts sowie den globalen Timer von Arduino, der auch auf Interrupts aufbaut. Viel genauer geht's nicht. Bzw. klar geht es noch genauer, ungefähr so, wie du es beschreibst, allerdings ist das völlig unnötig. Auch hier geht es nicht um maximale Genauigkeit, sondern um ausreichende, und diese ist um Größenordnungen höher als nötig. ```micros()``` löst auf vier Microsekunden genau auf.

Kurzes Rechenbeispiel: Bei 36 kmh (einfach zu rechnen) ist die Auflösung ~0,00144 kmh. Das ist ganz grob Faktor 100 besser als notwendig.

Und auch hier nehme ich daher lieber die lesbaren Funktionen, die sofort verständlich sind, statt irgendwelche wilden Register zu setzen, was keiner versteht und es auch inkompatibel zu anderen Plattformen macht.

**Timeouts**
Timeouts sind in jedem Fall notwendig und auch schon im Code drin. Sonst könnte man nur "geschlossene" Fahrzeuge messen, was ja quasi nie der Fall ist. Beim Messen der Rückseite ergibt sich dadurch auch das Problem, dass man die gemessene Geschwindigkeit erst anzeigen kann, wenn der Timeout abgelaufen ist. Wie gesagt, ich sehe keine Vorteile, auch die Rückseite zu messen. Aber wenn du das für dich implementieren willst, feel free 😉

**Comment by wucke13** [comment]
Alles klar :smile: Hab schon mal was für mich implementiert, was feiner war, auf ner ähnlichen Platform. Da gings um das messen von Zeitintervallen zwischen 500 und 1500 us, mit einer gewünschten Genauigkeit von 1 us.

Es wäre btw. noch cool ne Lizenz hinzuzufügen. Und es wäre allgemein praktisch, wenn es ein Kliemannsland Repo gäbe, wo alle in irgendeiner weise digital dokumentierten Projekte drin landen.
