### ISSUE TITLE
Circuit

### ISSUE THREAD

**Issue by Jeins98** [dschulte/geschwindigkeitsmessanlage#2]
Ich bin von der Schaltung etwas irritiert. Normalerweise verträgt der Arduino keine 12V am GPIO Eingang. Und mit den zwei Widerständen hast du einen Spannungsteiler gebaut.  Folglich würdest du so die Spannung auf eine verträgliche runterregeln. Nur sind dann die Widerstände vertauscht. So hättest du immer noch 10V, was meiner Erfahrung nach zu viel ist. Andersherum hättest du ~1V womit der Arduino auf jeden Fall zurecht kommt.

**Comment by dschulte** [comment]
ATmegas haben (so, wie eigentlich alle Microcontroller) Clampingdioden, die die Spannung begrenzen, sodass das klar geht, solange der Strom begrenzt wird. Dafür ist der 10k Widerstand gedacht. Der 100k Widerstand ist nicht primär als Spannungsteiler gedacht, sondern um den Pegel auf GND zu ziehen wenn die Lichtschranke geöffnet ist. In einer neueren Version benutze ich allerdings nur noch 100k Widerstände, da man so weniger verschiedene Bauteile hat. So ist man mit 6V dann auch näher am "Limit", wobei das bei dem Schaltungsaufbau keine Rolle spielt.
